# Pytorch Fundamentals

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

Tensors are a way to represent high dimensional numerical data in python.

Doc Link: https://pytorch.org/docs/stable/tensors.html

In [15]:
# Define a tensor.
TENSOR = torch.tensor([[7,2], [8,2]])

#print(f"Integer: {scalar.item()}")
# Get dimensions from the tensor.
print(f"Dimension: {TENSOR.ndim}")
# Get tensor back as python integer.
print(f"Shape: {TENSOR.shape}")

Dimension: 2
Shape: torch.Size([2, 2])


## Random tensors

Random tensors are important because a way for many neural networks to learn is to start with a random tensor and fit the tensor to better represent the data.

You can create random tensors using torch.rand.
Doc Link: https://pytorch.org/docs/stable/generated/torch.rand.html 

In [20]:
RAND_IMAGE_TENSOR = torch.rand(3,244,244)
RAND_IMAGE_TENSOR.shape

torch.Size([3, 244, 244])

## Common Tensor problems.

1. Tensors are not of right datatype. (cant compute with float 16 andd float 32)
    You can  cast a tensor using the .type() function. Example: tensor_var.type(torch.floast32)
2. Tensors are not of right shape. (You cant perform multiplication between matrices.)
3. Tensors are not on right device. (Device refers to the CPU or GPU.)

In [24]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4880, 0.7030, 0.1278],
        [0.3635, 0.6853, 0.0945],
        [0.3410, 0.6001, 0.0888]])

## Reshaping, Stacking, Squeezing and Unsqueezing Tensors

1. Reshaping: Reshapes an input tensor to a defined shape.
2. View: Return a view of input tensor but keep the same memory as original tensor.
3. Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack).
4. Squeeze: Removes all 1 dimensions from a tensor.
5. Unqueeze: Add a 1 dimension to a target tensor.
6. Permute: Return a view of input with dimensions in a certain way.

In [26]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [32]:
x_reshaped = x.reshape(1,9)
display(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(9,1)
display(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(3,3)
display(x_reshaped, x_reshaped.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

torch.Size([1, 9])

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

torch.Size([9, 1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

torch.Size([3, 3])

In [38]:
z= x.view(9,1)
z[0, :] = 9
z,x

(tensor([[9],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5]]),
 tensor([9, 5, 5, 5, 5, 5, 5, 5, 5]))