# Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

Tensors are a way to represent high dimensional numerical data in python.

Doc Link: https://pytorch.org/docs/stable/tensors.html

In [2]:
# Define a tensor.
TENSOR = torch.tensor([[7,2], [8,2]])

#print(f"Integer: {scalar.item()}")
# Get dimensions from the tensor.
print(f"Dimension: {TENSOR.ndim}")
# Get tensor back as python integer.
print(f"Shape: {TENSOR.shape}")

Dimension: 2
Shape: torch.Size([2, 2])


## Random tensors

Random tensors are important because a way for many neural networks to learn is to start with a random tensor and fit the tensor to better represent the data.

You can create random tensors using torch.rand.
Doc Link: https://pytorch.org/docs/stable/generated/torch.rand.html 

In [3]:
RAND_IMAGE_TENSOR = torch.rand(3,244,244)
RAND_IMAGE_TENSOR.shape

torch.Size([3, 244, 244])

## Common Tensor problems.

1. Tensors are not of right datatype. (cant compute with float 16 andd float 32)
    You can  cast a tensor using the .type() function. Example: tensor_var.type(torch.floast32)
2. Tensors are not of right shape. (You cant perform multiplication between matrices.)
3. Tensors are not on right device. (Device refers to the CPU or GPU.)

In [4]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8294, 0.2384, 0.9653],
        [0.1586, 0.0240, 0.4916],
        [0.5910, 0.1628, 0.7886]])

## Reshaping, Stacking, Squeezing and Unsqueezing Tensors

1. Reshaping: Reshapes an input tensor to a defined shape.
2. View: This operation returns the view of an input tensor. But the returned value occupies same memory as the original and hence any changes are propagated to the original value as well.
3. Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack).
4. Squeeze: Removes all 1 dimensions from a tensor.
5. Unqueeze: Add a 1 dimension to a target tensor.
6. Permute: This operation provides a view of the original tensor in a certain permutation (by swapping the positions as specified by the user).

In [5]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [6]:
x_reshaped = x.reshape(1,9)
display(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(9,1)
display(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(3,3)
display(x_reshaped, x_reshaped.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

torch.Size([1, 9])

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

torch.Size([9, 1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

torch.Size([3, 3])

In [7]:
z= x.view(9,1)
z[0, :] = 9
z,x

(tensor([[9],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([9, 2, 3, 4, 5, 6, 7, 8, 9]))

In [9]:
x = torch.rand(size=(224,224,3))
x_permuted = x.permute(2,0,1) # Shift the tensor where 0 becomes 2, 1 becomes 0 and 1 becomes 2
x_permuted

tensor([[[1.1312e-01, 3.5595e-01, 3.8025e-01,  ..., 2.3126e-02,
          1.1656e-01, 7.9352e-01],
         [8.1663e-01, 9.4457e-01, 3.3158e-01,  ..., 6.2241e-01,
          4.3960e-01, 6.2706e-01],
         [8.6535e-01, 8.5269e-01, 7.1332e-01,  ..., 5.3460e-01,
          7.9346e-01, 3.4390e-01],
         ...,
         [5.0144e-01, 1.4514e-01, 8.0385e-01,  ..., 2.3079e-01,
          1.7369e-01, 5.5101e-01],
         [7.0707e-01, 3.5843e-01, 9.3624e-01,  ..., 7.2680e-01,
          5.9055e-01, 5.4151e-01],
         [7.3497e-01, 7.5293e-01, 5.8296e-01,  ..., 4.6109e-01,
          5.2427e-01, 6.1827e-01]],

        [[4.4926e-01, 2.9433e-01, 5.2462e-01,  ..., 9.8232e-01,
          4.4959e-01, 5.7567e-01],
         [3.3631e-01, 2.0952e-01, 7.2137e-01,  ..., 8.3679e-01,
          1.7695e-01, 6.7037e-01],
         [1.2483e-01, 6.5410e-01, 2.9455e-01,  ..., 5.5958e-01,
          7.7700e-01, 6.2490e-01],
         ...,
         [3.6615e-01, 3.8577e-01, 6.2018e-01,  ..., 2.6664e-01,
          9.364

## Reproducibility

How a neural network learns.
Start with random numbers -> Tensor operations -> Update random number and make the representation better in a loop.

But to introduce reproducibility we need to ensure that random generator doesnt create a new random number everytime.

This is done by using a random seed value.
Once this seed value is fixed the random number generation can be reproduced.